name: m3u8
description: prase m3u8 content
version: 1.0.0
homepage: https://github.com/hellojukay/m3u8.dart
repository: https://github.com/hellojukay/m3u8.dart

environment:
  sdk: '>=2.18.4 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
